export  const RSS_FEEDS = [

  "http://feeds.bbci.co.uk/news/world/rss.xml",
  "https://feeds.npr.org/1001/rss.xml",
  "http://rss.cnn.com/rss/edition.rss ",
  " https://www.theguardian.com/world/rss",
  "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml ",
    "https://www.aljazeera.com/xml/rss/all.xml",    
    "https://www.reutersagency.com/feed/?best-topics=world&post_type=best",
    "https://www.wired.com/feed/category/science/latest/rss",
    "https://www.scientificamerican.com/feed/",
    "https://www.space.com/feeds/all",
    "https://www.nasa.gov/rss/dyn/breaking_news.rss",
    "https://www.nature.com/subjects/space/rss",    
    "https://www.nature.com/subjects/earth-sciences/rss",
    "https://www.nature.com/subjects/environment/rss",
    "https://www.nature.com/subjects/climate-change/rss",
    
    "https://www.nature.com/subjects/oceans/rss",
    "https://www.nature.com/subjects/astronomy/rss",
    "https://www.nature.com/subjects/geology/rss",
    "https://www.nature.com/subjects/meteorology/rss",
    "https://www.nature.com/subjects/paleontology/rss",
    "https://www.nature.com/subjects/geophysics/rss",
    "https://www.nature.com/subjects/hydrology/rss",
    "https://www.nature.com/subjects/glaciology/rss",
    
    "https://www.nature.com/subjects/volcanology/rss",
    "https://www.bloomberg.com/feed/podcast/etf-report.xml",
    "https://www.bloomberg.com/feed/podcast/money-movers.xml",
    "https://www.espn.com/espn/rss/news",
    "https://www.skysports.com/rss/12040",
    " https://www.imdb.com/news/feed",
    "https://www.gamespot.com/feeds/mashup/",
    "http://www.mtv.com/news/rss/",
    "https://www.who.int/feeds/entity/mediacentre/news/en/rss.xml",
    "https://www.travelandleisure.com/rss",
    "https://www.cnet.com/rss/news/",
    "https://www.theverge.com/rss/index.xml",
    "https://www.engadget.com/rss.xml", 
    "https://www.techradar.com/rss",
    "https://www.gizmodo.com/rss",
    "https://www.pcgamer.com/rss/",
    "https://www.polygon.com/rss/index.xml",    
    "https://www.popsci.com/rss.xml",
    "https://www.newscientist.com/feed/home/",
    "https://www.livescience.com/feeds/all",
    "https://www.sciencenews.org/feed",
    "https://www.mentalfloss.com/rss",
    "https://www.smithsonianmag.com/rss",
    

];